apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab5
resources:
  - namespace.yaml
  - configmap.yaml
  - valkey-auth-secret.yaml
  - valkeycluster.yaml
  - valkey-seed-service.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - servicemonitor.yaml
