apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: dotnet-webapp-valkey-password
  labels:
    app.kubernetes.io/name: cache
    app.kubernetes.io/part-of: lab5
spec:
  length: 32
  digits: 8
  symbols: 4
  symbolCharacters: "-_@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dotnet-webapp-valkey-auth
  labels:
    app.kubernetes.io/name: cache
    app.kubernetes.io/part-of: lab5
spec:
  refreshPolicy: CreatedOnce
  target:
    name: dotnet-webapp-valkey-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: cache
          app.kubernetes.io/part-of: lab5
      data:
        password: "{{ .password }}"
        connection: "valkey-seed:6379,user=dotnet-webapp,password={{ .password }},abortConnect=false"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: dotnet-webapp-valkey-password
